begin;

create extension if not exists pgtap with schema extensions;
select no_plan();

-- Phase 3 isolated synthetic lineage.
-- target user:       b3000000-0000-4000-8000-000000000001
-- control user:      b3000000-0000-4000-8000-000000000002
-- target operation:  generated by the database and aligned by user + request key
-- target project:    b3300000-0000-4000-8000-000000000001
-- control project:   b3300000-0000-4000-8000-000000000002
insert into auth.users (
  id,instance_id,aud,role,email,encrypted_password,email_confirmed_at,
  raw_app_meta_data,raw_user_meta_data,created_at,updated_at
) values
  ('b3000000-0000-4000-8000-000000000001','00000000-0000-0000-0000-000000000000',
   'authenticated','authenticated','phase3-target@example.test','',now(),'{}','{}',now(),now()),
  ('b3000000-0000-4000-8000-000000000002','00000000-0000-0000-0000-000000000000',
   'authenticated','authenticated','phase3-control@example.test','',now(),'{}','{}',now(),now());
insert into public.users(id) values
  ('b3000000-0000-4000-8000-000000000001'),
  ('b3000000-0000-4000-8000-000000000002');

insert into public.github_installations(
  id,user_id,installation_id,github_account_id,github_account_login,
  account_type,repository_selection,status,last_verified_at
) values
  ('b3100000-0000-4000-8000-000000000001','b3000000-0000-4000-8000-000000000001',930001,930001,'phase3-target','User','selected','active',now()),
  ('b3100000-0000-4000-8000-000000000002','b3000000-0000-4000-8000-000000000002',930002,930002,'phase3-control','User','selected','active',now());
insert into public.selected_repositories(
  id,user_id,github_installation_id,github_repository_id,owner_login,name,
  full_name,visibility,is_private,is_fork,is_archived,is_disabled,default_branch
) values
  ('b3200000-0000-4000-8000-000000000001','b3000000-0000-4000-8000-000000000001','b3100000-0000-4000-8000-000000000001',930101,'synthetic','phase3-target','synthetic/phase3-target','private',true,false,false,false,'main'),
  ('b3200000-0000-4000-8000-000000000002','b3000000-0000-4000-8000-000000000002','b3100000-0000-4000-8000-000000000002',930102,'synthetic','phase3-control','synthetic/phase3-control','private',true,false,false,false,'main');
insert into public.projects(id,user_id,selected_repository_id,core_goal,current_stage_goal,status) values
  ('b3300000-0000-4000-8000-000000000001','b3000000-0000-4000-8000-000000000001','b3200000-0000-4000-8000-000000000001','Phase 3 target','Delete safely','in_development'),
  ('b3300000-0000-4000-8000-000000000002','b3000000-0000-4000-8000-000000000002','b3200000-0000-4000-8000-000000000002','Phase 3 control','Remain unchanged','in_development');
insert into public.sync_runs(id,project_id,idempotency_key,trigger_source,status,version,queued_at,started_at,created_at,updated_at) values
  ('b3400000-0000-4000-8000-000000000001','b3300000-0000-4000-8000-000000000001','phase3:queued','manual','queued',1,now(),null,now(),now()),
  ('b3400000-0000-4000-8000-000000000002','b3300000-0000-4000-8000-000000000002','phase3:control','manual','queued',1,now(),null,now(),now()),
  ('b3400000-0000-4000-8000-000000000003','b3300000-0000-4000-8000-000000000001','phase3:running','manual','running',1,now()-interval '1 minute',now(),now()-interval '1 minute',now());
insert into public.project_sync_dispatches(id,project_id,sync_run_id,request_identity,trigger_source,requested_at,created_at,updated_at) values
  ('b3500000-0000-4000-8000-000000000001','b3300000-0000-4000-8000-000000000001','b3400000-0000-4000-8000-000000000001','phase3:queued','manual',now(),now(),now()),
  ('b3500000-0000-4000-8000-000000000002','b3300000-0000-4000-8000-000000000002','b3400000-0000-4000-8000-000000000002','phase3:control','manual',now(),now(),now());
insert into public.github_webhook_deliveries(
  id,delivery_id,body_sha256,event_name,installation_id,repository_id,
  repository_full_name,project_id,internal_event_id,status,received_at
) values
  ('b3800000-0000-4000-8000-000000000001','b3810000-0000-4000-8000-000000000001',repeat('a',64),'issues',930001,930101,'synthetic/phase3-target','b3300000-0000-4000-8000-000000000001','github-webhook:b3820000-0000-4000-8000-000000000001','pending',now()),
  ('b3800000-0000-4000-8000-000000000002','b3810000-0000-4000-8000-000000000002',repeat('b',64),'issues',930002,930102,'synthetic/phase3-control','b3300000-0000-4000-8000-000000000002','github-webhook:b3820000-0000-4000-8000-000000000002','pending',now());
insert into public.project_briefs(id,user_id,project_id,range_start,range_end,status) values
  ('b3900000-0000-4000-8000-000000000001','b3000000-0000-4000-8000-000000000001','b3300000-0000-4000-8000-000000000001',now()-interval '1 day',now(),'pending'),
  ('b3900000-0000-4000-8000-000000000002','b3000000-0000-4000-8000-000000000002','b3300000-0000-4000-8000-000000000002',now()-interval '1 day',now(),'pending');
insert into public.energy_ledger_entries(user_id,business_date,idempotency_key,entry_type,amount,delta) values
  ('b3000000-0000-4000-8000-000000000001',current_date,'phase3-grant-target','grant',10,10),
  ('b3000000-0000-4000-8000-000000000002',current_date,'phase3-grant-control','grant',10,10);
insert into public.energy_reservations(id,user_id,project_id,business_date,request_key,amount,status,created_at) values
  ('b3600000-0000-4000-8000-000000000001','b3000000-0000-4000-8000-000000000001','b3300000-0000-4000-8000-000000000001',current_date,'phase3:reserved',3,'reserved',now()),
  ('b3600000-0000-4000-8000-000000000002','b3000000-0000-4000-8000-000000000002','b3300000-0000-4000-8000-000000000002',current_date,'phase3:control',3,'reserved',now());
insert into public.energy_ledger_entries(user_id,project_id,business_date,idempotency_key,entry_type,amount,delta,reservation_id) values
  ('b3000000-0000-4000-8000-000000000001','b3300000-0000-4000-8000-000000000001',current_date,'phase3-reserved-target','reserved',3,-3,'b3600000-0000-4000-8000-000000000001'),
  ('b3000000-0000-4000-8000-000000000002','b3300000-0000-4000-8000-000000000002',current_date,'phase3-reserved-control','reserved',3,-3,'b3600000-0000-4000-8000-000000000002');
insert into public.ai_invocations(id,user_id,project_id,feature,status,reservation_id,created_at,started_at) values
  ('b3700000-0000-4000-8000-000000000001','b3000000-0000-4000-8000-000000000001','b3300000-0000-4000-8000-000000000001','project_brief','pending','b3600000-0000-4000-8000-000000000001',now(),now()),
  ('b3700000-0000-4000-8000-000000000002','b3000000-0000-4000-8000-000000000002','b3300000-0000-4000-8000-000000000002','project_brief','pending','b3600000-0000-4000-8000-000000000002',now(),now());

create temporary table phase3_receipts(result jsonb);
insert into phase3_receipts
select public.request_account_deletion(
  'b3000000-0000-4000-8000-000000000001',
  'phase3:request:one',
  'DELETE ACCOUNT b3000000-0000-4000-8000-000000000001'
);

select is((select result->>'status' from phase3_receipts),'deletion_pending','request enters deletion_pending');
select is((select (result->>'safelyRetryable')::boolean from phase3_receipts),true,'request is safely retryable');
select ok(
  (select (result->>'dueAt')::timestamptz-(result->>'requestedAt')::timestamptz=interval '7 days' from phase3_receipts),
  'database authoritative due time is exactly seven days after request'
);
select is((select status from public.sync_runs where id='b3400000-0000-4000-8000-000000000001'),'cancelled','request immediately cancels queued Sync');
select results_eq(
  $$select status,error_code from public.sync_runs where id='b3400000-0000-4000-8000-000000000003'$$,
  $$values ('failed'::text,'account_deletion_pending'::text)$$,
  'request immediately fails closed a running Sync'
);
select results_eq(
  $$select dispatch_status,safe_error_code from public.project_sync_dispatches where id='b3500000-0000-4000-8000-000000000001'$$,
  $$values ('cancelled'::text,'account_deletion_pending'::text)$$,
  'request immediately cancels pending dispatch'
);
select is((select status from public.github_webhook_deliveries where id='b3800000-0000-4000-8000-000000000001'),'ignored','request immediately terminates pending Webhook work');
select results_eq(
  $$select status,failure_stage,error_code from public.project_briefs where id='b3900000-0000-4000-8000-000000000001'$$,
  $$values ('failed'::text,'authorization'::text,'account_deletion_pending'::text)$$,
  'request immediately terminates pending Project Brief'
);
select results_eq(
  $$select status,failure_stage,error_code from public.energy_reservations where id='b3600000-0000-4000-8000-000000000001'$$,
  $$values ('released'::text,'authorization'::text,'account_deletion_pending'::text)$$,
  'request immediately releases reserved Energy'
);
select is((select status from public.ai_invocations where id='b3700000-0000-4000-8000-000000000001'),'failed','request immediately terminates pending AI');
select throws_ok(
  $$select public.create_sync_run('b3300000-0000-4000-8000-000000000001','phase3:new-sync','manual')$$,
  'P0001','account_deletion_pending','new Sync fails closed after request'
);

select is(
  public.request_account_deletion(
    'b3000000-0000-4000-8000-000000000001','phase3:request:one',
    'DELETE ACCOUNT b3000000-0000-4000-8000-000000000001'
  )->>'operationId',
  (select result->>'operationId' from phase3_receipts),
  'same request key replays the same operation'
);
select throws_ok(
  $$select public.request_account_deletion(
    'b3000000-0000-4000-8000-000000000001','phase3:request:conflict',
    'DELETE ACCOUNT b3000000-0000-4000-8000-000000000001'
  )$$,
  'P0001','account_deletion_idempotency_conflict','different key cannot replace a pending operation'
);

select is(
  public.cancel_account_deletion(
    'b3000000-0000-4000-8000-000000000001',
    (select (result->>'operationId')::uuid from phase3_receipts)
  )->>'status','active','cancel inside the window restores active'
);
select lives_ok(
  $$select public.create_sync_run('b3300000-0000-4000-8000-000000000001','phase3:after-cancel','manual')$$,
  'new Sync is allowed after legal cancellation'
);

truncate phase3_receipts;
insert into phase3_receipts
select public.request_account_deletion(
  'b3000000-0000-4000-8000-000000000001','phase3:request:two',
  'DELETE ACCOUNT b3000000-0000-4000-8000-000000000001'
);
select is(
  public.claim_account_deletion(
    (select (result->>'operationId')::uuid from phase3_receipts),interval '5 minutes'
  )->>'outcome','not_due','claim before due is rejected without state transition'
);
update public.account_deletion_operations
set due_at=fixture_time.value,
    requested_at=fixture_time.value-interval '7 days'
from (select clock_timestamp()-interval '1 second' as value) fixture_time
where operation_id=(select (result->>'operationId')::uuid from phase3_receipts);
create temporary table phase3_claim as
select public.claim_account_deletion(
  (select (result->>'operationId')::uuid from phase3_receipts),interval '5 minutes'
) result;
select is((select result->>'status' from phase3_claim),'deleting','due claim enters deleting');
select throws_ok(
  $$select public.cancel_account_deletion(
    'b3000000-0000-4000-8000-000000000001',
    (select (result->>'operationId')::uuid from phase3_receipts)
  )$$,
  'P0001','account_deletion_cancel_window_closed','claimed deletion cannot be cancelled'
);

select is(
  public.cleanup_account_business_data(
    (select (result->>'operationId')::uuid from phase3_receipts),
    (select (result->>'leaseToken')::uuid from phase3_claim)
  )->>'outcome','deleted','business cleanup returns a durable receipt'
);
select is((select count(*)::text from public.users where id='b3000000-0000-4000-8000-000000000001'),'0','target public user is deleted');
select is((select count(*)::text from public.projects where user_id='b3000000-0000-4000-8000-000000000001'),'0','target business project subtree has no survivor');
select is((select count(*)::text from auth.users where id='b3000000-0000-4000-8000-000000000001'),'1','database cleanup does not pretend Auth Admin deletion succeeded');
select is(
  public.complete_account_deletion(
    (select (result->>'operationId')::uuid from phase3_receipts),
    (select (result->>'leaseToken')::uuid from phase3_claim),
    'auth_failed',repeat('a',64),'account_deletion_auth_identity_delete_failed'
  )->>'status','deletion_failed','Auth partial failure is durable and retryable'
);
create temporary table phase3_retry as
select public.claim_account_deletion(
  (select (result->>'operationId')::uuid from phase3_receipts),interval '5 minutes'
) result;
select is((select result->>'status' from phase3_retry),'deleting','failed deletion can be claimed for retry');
select is(
  public.cleanup_account_business_data(
    (select (result->>'operationId')::uuid from phase3_receipts),
    (select (result->>'leaseToken')::uuid from phase3_retry)
  )->>'outcome','already_absent','business cleanup replay is a no-op'
);
select is(
  public.complete_account_deletion(
    (select (result->>'operationId')::uuid from phase3_receipts),
    (select (result->>'leaseToken')::uuid from phase3_retry),
    'auth_already_absent',repeat('b',64),null
  )->>'status','deleted','already absent Auth identity converges to deleted'
);
select is(
  public.claim_account_deletion(
    (select (result->>'operationId')::uuid from phase3_receipts),interval '5 minutes'
  )->>'outcome','completed','completed deletion job replays as a no-op'
);

select results_eq(
  $$select
    (select count(*)::text from public.users where id='b3000000-0000-4000-8000-000000000002'),
    (select count(*)::text from public.projects where id='b3300000-0000-4000-8000-000000000002'),
    (select status::text from public.sync_runs where id='b3400000-0000-4000-8000-000000000002'),
    (select dispatch_status::text from public.project_sync_dispatches where id='b3500000-0000-4000-8000-000000000002'),
    (select status::text from public.github_webhook_deliveries where id='b3800000-0000-4000-8000-000000000002'),
    (select status::text from public.project_briefs where id='b3900000-0000-4000-8000-000000000002'),
    (select status::text from public.energy_reservations where id='b3600000-0000-4000-8000-000000000002'),
    (select sum(delta)::text from public.energy_ledger_entries where user_id='b3000000-0000-4000-8000-000000000002')$$,
  $$values ('1'::text,'1'::text,'queued'::text,'pending'::text,'pending'::text,'pending'::text,'reserved'::text,'7'::text)$$,
  'other user and project remain unchanged'
);
select is((select count(*)::text from public.account_deletion_operations where user_id='b3000000-0000-4000-8000-000000000001'),'1','one minimal tombstone remains');
select ok(
  not exists (
    select 1 from public.account_deletion_operations operation
    where operation.user_id='b3000000-0000-4000-8000-000000000001'
      and row_to_json(operation)::text ~* 'phase3-target@example|synthetic/phase3|github_login|access_token|refresh_token'
  ),
  'tombstone contains no email, repository, login, or token content'
);

select * from finish();
rollback;
