import { describe, expect, it, vi } from "vitest";
vi.mock("server-only", () => ({}));
import { GitHubProjectRepositoryMetadataReader, githubProjectRepositoryMetadataReaderContract } from "./github-project-repository-metadata-reader";
const at = "2026-08-07T02:00:00.000Z";
const context = { projectId: "11111111-1111-4111-8111-111111111111", repository: { githubObjectId: "91001", owner: "synthetic", name: "repository", fullName: "synthetic/repository", visibility: "private" as const, isPrivate: true, isFork: false, isArchived: false, isDisabled: false, defaultBranch: "main", sourceUpdatedAt: at, sourceVersion: "old" }, installation: { installationId: 81_001, status: "active" as const } };
describe("github-project-repository-metadata-reader.v1", () => {
  it("maps trusted metadata with deterministic version", async () => { const gateway = { listAllForInstallation: vi.fn(async () => ({ repositorySelection: "selected" as const, totalCount: 1, loadedAt: at, repositories: [{ id: 91_001, name: "repository", fullName: "synthetic/repository", ownerLogin: "synthetic", isPrivate: true, isFork: false, isArchived: false, isDisabled: false, visibility: "private" as const, defaultBranch: "main" }] })) }; const reader = new GitHubProjectRepositoryMetadataReader(gateway); const first = await reader.read({ context, readAt: at }); const replay = await reader.read({ context, readAt: "2026-08-08T02:00:00.000Z" }); expect(githubProjectRepositoryMetadataReaderContract).toBe("github-project-repository-metadata-reader.v1"); expect(first.sourceVersion).toMatch(/^[0-9a-f]{64}$/); expect(replay.sourceVersion).toBe(first.sourceVersion); expect(first).not.toHaveProperty("rawPayload"); });
  it("rejects untrusted repository mapping", async () => { const reader = new GitHubProjectRepositoryMetadataReader({ listAllForInstallation: vi.fn(async () => ({ repositorySelection: "selected" as const, totalCount: 0, loadedAt: at, repositories: [] })) }); await expect(reader.read({ context, readAt: at })).rejects.toThrow("github_activity_not_found"); });
});
