import { describe, expect, it, vi } from "vitest";
import { WebhookSynchronizationRuntime, webhookSynchronizationRuntimeContract } from "./webhook-sync-use-cases";
import type { ProjectSynchronizationResult } from "./project-sync-use-cases";
const projectId = "11111111-1111-4111-8111-111111111111";
const runId = "22222222-2222-4222-8222-222222222222";
const deliveryId = "33333333-3333-4333-8333-333333333333";
const at = "2026-08-07T02:00:00.000Z";
const event = { version: "github-webhook-event.v1", eventId: `github-webhook:${deliveryId}`, idempotencyKey: `github-webhook:${deliveryId}`, deliveryId, bodySha256: "a".repeat(64), eventName: "issues", kind: "github.issue.v1", action: "opened", projectId, installationId: 81_001, repositoryId: 91_001, repositoryFullName: "synthetic/repository", githubObjectId: "101", receivedAt: at, processingVersion: 2 } as const;
const completed: ProjectSynchronizationResult = { syncRunId: runId, status: "completed", groups: [], errorCode: null, retryable: false, authorizationRevoked: false, replayed: false };
function fixture(status: "dispatched" | "processing" | "completed" = "dispatched") {
  const deliveries = { register: vi.fn(async () => ({ outcome: "duplicate" as const, status, version: status === "dispatched" ? 3 : 4, projectId })), claimDispatch: vi.fn(), completeDispatch: vi.fn(), completeInstallation: vi.fn(), claimProcessing: vi.fn(async () => ({ claimed: true, status: "processing" as const, version: 4 })), completeProcessing: vi.fn(async () => ({ outcome: "completed" as const, status: "completed" as const, version: 5 })), failProcessing: vi.fn(async () => ({ outcome: "failed" as const, status: "failed" as const, version: 5 })) };
  const requests = { request: vi.fn(async () => ({ outcome: "new" as const, projectId, syncRunId: runId, syncRunStatus: "queued" as const, dispatchState: "pending" as const, dispatchVersion: 1 })), claimDispatch: vi.fn(async () => ({ claimed: true, version: 2 })), completeDispatch: vi.fn(async () => undefined) };
  const dispatcher = { dispatch: vi.fn(async () => ({ providerJobId: "provider-job-001" })) };
  const executor = { execute: vi.fn(async () => completed) };
  return { runtime: new WebhookSynchronizationRuntime({ requests, deliveries, dispatcher, executor, clock: { now: () => new Date(at) } }), deliveries, requests, dispatcher, executor };
}
describe("github-webhook-synchronization-runtime.v1", () => {
  it("creates a durable webhook run, claims delivery and dispatches stable project job", async () => { const f = fixture(); await expect(f.runtime.request(event)).resolves.toEqual({ outcome: "accepted", syncRunId: runId, providerJobId: "provider-job-001" }); expect(webhookSynchronizationRuntimeContract).toBe("github-webhook-synchronization-runtime.v1"); expect(f.requests.request).toHaveBeenCalledWith(expect.objectContaining({ triggerSource: "webhook", requestIdentity: `webhook:${deliveryId}` })); expect(f.deliveries.claimProcessing).toHaveBeenCalledWith(expect.objectContaining({ deliveryId, syncRunId: runId, expectedVersion: 3 })); expect(f.dispatcher.dispatch).toHaveBeenCalledWith(expect.objectContaining({ triggerSource: "webhook", webhookDelivery: expect.objectContaining({ deliveryId, processingVersion: 4 }) })); });
  it("makes completed delivery replay a no-op", async () => { const f = fixture("completed"); await expect(f.runtime.request(event)).resolves.toMatchObject({ outcome: "duplicate" }); expect(f.requests.request).not.toHaveBeenCalled(); expect(f.dispatcher.dispatch).not.toHaveBeenCalled(); });
  it("completes delivery only after project SyncRun succeeds", async () => { const f = fixture("processing"); const job = { version: "background-job.v1", jobType: "project.sync.requested.v1", jobId: runId, projectId, syncRunId: runId, idempotencyKey: `sync-request:webhook:${deliveryId}`, correlationId: `sync:${runId}`, requestedAt: at, triggerSource: "webhook", webhookDelivery: { deliveryId, bodySha256: "a".repeat(64), eventName: "issues", action: "opened", installationId: 81_001, repositoryId: 91_001, repositoryFullName: "synthetic/repository", internalEventId: `github-webhook:${deliveryId}`, processingVersion: 4 } }; await expect(f.runtime.execute({ job })).resolves.toEqual(completed); expect(f.deliveries.completeProcessing).toHaveBeenCalledWith(expect.objectContaining({ deliveryId, syncRunId: runId, expectedVersion: 4 })); });
  it("records allowlisted retryable failure and rethrows safe code", async () => { const f = fixture("processing"); f.executor.execute.mockResolvedValue({ ...completed, status: "partial", errorCode: "github_activity_timeout", retryable: true }); const job = { version: "background-job.v1", jobType: "project.sync.requested.v1", jobId: runId, projectId, syncRunId: runId, idempotencyKey: `sync-request:webhook:${deliveryId}`, correlationId: `sync:${runId}`, requestedAt: at, triggerSource: "webhook", webhookDelivery: { deliveryId, bodySha256: "a".repeat(64), eventName: "issues", action: "opened", installationId: 81_001, repositoryId: 91_001, repositoryFullName: "synthetic/repository", internalEventId: `github-webhook:${deliveryId}`, processingVersion: 4 } }; await expect(f.runtime.execute({ job })).rejects.toThrow("github_activity_timeout"); expect(f.deliveries.failProcessing).toHaveBeenCalledWith(expect.objectContaining({ safeErrorCode: "github_activity_timeout" })); });
});
