import { describe, expect, it, vi } from "vitest";
vi.mock("server-only", () => ({}));
import { Inngest } from "inngest";
import { createInngestSynchronizationFunctions, createInngestSynchronizationHandlers, inngestSynchronizationFunctionDefinitions, inngestSynchronizationRuntimeContract } from "./inngest-runtime";
const projectId = "11111111-1111-4111-8111-111111111111";
const runId = "22222222-2222-4222-8222-222222222222";
const at = "2026-08-07T02:00:00.000Z";
const job = (triggerSource: "first_sync" | "webhook" | "reconciliation" | "manual") => ({ version: "background-job.v1", jobType: "project.sync.requested.v1", jobId: runId, projectId, syncRunId: runId, idempotencyKey: `sync-request:${triggerSource}`, correlationId: `sync:${runId}`, requestedAt: at, triggerSource, webhookDelivery: triggerSource === "webhook" ? { deliveryId: "33333333-3333-4333-8333-333333333333", bodySha256: "a".repeat(64), eventName: "issues", action: "opened", installationId: 81_001, repositoryId: 91_001, repositoryFullName: "synthetic/repository", internalEventId: "github-webhook:33333333-3333-4333-8333-333333333333", processingVersion: 4 } : null });
function fixture() { const firstSync = { execute: vi.fn(async () => "first") }; const projectSync = { execute: vi.fn(async () => "project") }; const webhooks = { request: vi.fn(async () => "webhook-request"), execute: vi.fn(async () => "webhook-execute") }; const daily = { handle: vi.fn(async () => "daily") }; return { dependencies: { firstSync, projectSync, webhooks, daily }, firstSync, projectSync, webhooks, daily }; }
describe("inngest-synchronization-runtime.v1", () => {
  it("registers project, webhook and real daily cron production functions", () => { const f = fixture(); const functions = createInngestSynchronizationFunctions(new Inngest({ id: "synthetic-runtime", eventKey: "synthetic-event-key", signingKey: "signkey-test-synthetic" }), f.dependencies); expect(inngestSynchronizationRuntimeContract).toBe("inngest-synchronization-runtime.v1"); expect(functions).toHaveLength(3); expect(inngestSynchronizationFunctionDefinitions.map((item) => item.id)).toEqual(["executor-project-sync-consumer", "executor-github-webhook-consumer", "executor-daily-reconciliation"]); expect(inngestSynchronizationFunctionDefinitions[2]).toMatchObject({ trigger: "cron:0 2 * * *", idempotency: "domain:reconciliation:<UTC-day>" }); });
  it.each(["first_sync", "webhook", "reconciliation", "manual"] as const)("routes %s to trigger-correct real executor", async (trigger) => { const f = fixture(); const handlers = createInngestSynchronizationHandlers(f.dependencies); await handlers.projectSync(job(trigger)); expect(f.firstSync.execute).toHaveBeenCalledTimes(trigger === "first_sync" ? 1 : 0); expect(f.webhooks.execute).toHaveBeenCalledTimes(trigger === "webhook" ? 1 : 0); expect(f.projectSync.execute).toHaveBeenCalledTimes(["reconciliation", "manual"].includes(trigger) ? 1 : 0); });
  it("calls daily scheduler with canonical UTC and rejects invalid schedule", async () => { const f = fixture(); const handlers = createInngestSynchronizationHandlers(f.dependencies); await expect(handlers.daily(at)).resolves.toBe("daily"); expect(f.daily.handle).toHaveBeenCalledWith({ scheduledAt: at }); await expect(handlers.daily("not-a-time")).rejects.toThrow("reconciliation_schedule_invalid"); });
  it("strictly rejects an extra job field before any executor", async () => { const f = fixture(); const handlers = createInngestSynchronizationHandlers(f.dependencies); await expect(handlers.projectSync({ ...job("manual"), rawPayload: {} })).rejects.toThrow("background_job_invalid_request"); expect(f.projectSync.execute).not.toHaveBeenCalled(); });
});
